task: 'mix_abmil'
train_data: '/home/omnisky/sde/NanTH/camlyon16/training/features'
test_data: '/home/omnisky/sde/NanTH/camlyon16/testing/features'
#train_data: '/home/omnisky/sde/NanTH/camlyon16/training/features'
#test_data: '/home/omnisky/sde/NanTH/camlyon16/testing/features'
output: ./output'
batch_size: 1
sample_size: 256
epochs: 160
workers: 1
loss: 'ce'
test_every: 5
weight_decay: 1.e-4
k: 512
lr: 1.e-4
image_size: 224
cuda: '2'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 5
seed: 1
asynchronous: 0
feature_dim: 1024
data_num: 120