task: 'clam_sb'
train_data: '/home/omnisky/sde/NanTH/IRL_Data/all_slide/features'
test_data: '/home/omnisky/sde/NanTH/IRL_Data/all_slide/features'
output: './outputs'
batch_size: 1
size_arg: "small"
gate: True
epochs: 100
workers: 4
loss: 'ce'
test_every: 5
weight_decay: 1.e-5
k: 10
bag_weight: 0.7
lr: 1.e-4
image_size: 224
cuda: '1'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 5
seed: 2333
