task: 'max_pooling_mil'
#train_data: '/home/omnisky/sde/NanTH/IRL_Data/all_slide/epr/no_see'
train_data: '/home/omnisky/sde/NanTH/IRL_Data/all_slide/features'
test_data: '/home/omnisky/sde/NanTH/IRL_Data/all_slide/features'
output: './outputs'
batch_size: 512
epochs: 100
workers: 1
loss: 'ce'
test_every: 5
weight_decay: 1.e-4
k: 2
lr: 1.e-4
image_size: 224
cuda: '0'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 5
seed: 2333
data_num: 20