task: 'mil_rnn'
train_data: '/home/omnisky/verybigdisk/wissingcc/multi_class_mil/Baseline/Data/train'
test_data: '/home/omnisky/verybigdisk/wissingcc/multi_class_mil/Baseline/Data/test'
output: '/home/omnisky/verybigdisk/wissingcc/multi_class_mil/Baseline/outputs'
batch_size: 128
epochs: 50
embed_dim: 128
loss: 'ce'
workers: 4
test_every: 5
weight_decay: 1.e-4
k: 10
lr: 1.e-4
image_size: 224
cuda: '0'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 2
seed: 2333
