task: 'mix_rnn'
train_data: '/home/omnisky/sde/NanTH/camlyon16/training/features'
test_data: '/home/omnisky/sde/NanTH/camlyon16/testing/features'
output: './outputs'
batch_size: 128
epochs: 200
embed_dim: 128
loss: 'ce'
workers: 4
test_every: 5
weight_decay: 1.e-4
k: 32
lr: 1.e-5
image_size: 224
cuda: '0'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 2
seed: 2333
asynchronous: 0
feature_dim: 1024
