task: 'stable_transmil'
train_data: '/home/omnisky/hdd_15T_sdd/NanTH/Result/CLAM/level3/train/features_0805'
test_data: '/home/omnisky/hdd_15T_sdd/NanTH/Result/CLAM/level3/test/feature_res'
output: ./output'
batch_size: 1
sample_size: 256
epochs: 300
workers: 4
loss: 'ce'
test_every: 5
weight_decay: 2.e-4
k: 10
lr: 1.e-4
image_size: 224
cuda: '1'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 2
seed: 2333