task: 'supvision'
train_data: '/home/omnisky/sde/NanTH/IRL_Data/all_slide/annoted'
test_data: '/home/omnisky/sde/NanTH/IRL_Data/all_slide/features'
output: './outputs'
batch_size: 2048
epochs: 100
workers: 4
loss: 'ce'
test_every: 5
weight_decay: 5.e-4
k: 10
lr: 1.e-5
image_size: 224
cuda: '2'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 5
seed: 2333
