task: 'transmil'
train_data: '/home/omnisky/verybigdisk/wissingcc/multi_class_mil/Baseline/Data/train'
test_data: '/home/omnisky/verybigdisk/wissingcc/multi_class_mil/Baseline/Data/test'
output: ./output'
batch_size: 1
sample_size: 256
epochs: 50
workers: 4
loss: 'ce'
test_every: 5
weight_decay: 1.e-4
k: 10
lr: 1.e-4
image_size: 224
cuda: '0'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 4
seed: 2333