task: 'transmil'
train_data: '/home/omnisky/sde/NanTH/camlyon16/training/features'
test_data: '/home/omnisky/sde/NanTH/camlyon16/testing/features'
output: ./output'
batch_size: 1
sample_size: 256
epochs: 50
workers: 4
loss: 'ce'
test_every: 5
weight_decay: 1.e-4
k: 16
lr: 1.e-4
image_size: 224
cuda: '0'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 2
seed: 2333